import math
import platform
import os
import time

BLACK = '\033[30m'
RED = '\033[31m'
GREEN = '\033[32m'
YELLOW = '\033[33m'
BLUE = '\033[34m'
MAGENTA = '\033[35m'
CYAN = '\033[36m'
BLANCO = '\033[37m'
RESET = '\033[39m'

print(MAGENTA+" ∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆")
print(BLANCO+ " ∆∆∆     ∆∆      ∆∆∆∆∆                                                              ∆∆∆")
print(MAGENTA+" ∆∆∆  ∆∆∆∆∆  ∆∆∆∆∆∆∆∆∆ ®® ®® 44444 77777 yyyyy iiiii vvvvv xxxxx 23361      √       ∆∆∆")
print(BLANCO+ " ∆∆∆     ∆∆    ∆∆∆∆∆∆∆ ® ® ® 4   4   7   7   7   i   v     x     0         √ \      ∆∆∆")
print(MAGENTA+" ∆∆∆∆∆∆  ∆∆  ∆∆∆∆∆∆∆∆∆ ®   ® 4   4   7   7   7   i   v     xxx   78850    √   \     ∆∆∆")
print(BLANCO+ " ∆∆∆     ∆∆  ∆∆∆∆∆  ∆∆ ®   ® 44444   7   7  7    i   v     x         0   √     \    ∆∆∆")
print(MAGENTA+" ∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆ ®   ® 4   4   7   7   7 iiiii vvvvv xxxxx 78889  √_______\   ∆∆∆")
print(BLANCO+ " ∆∆              ∆∆∆∆∆                                                              ∆∆∆")
print(MAGENTA+" ∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆")
print(CYAN+   " ¶¶¶¶¶¶¶¶¶¶¶¶         creado por/created by: Sorft Faricson Scripts        ¶¶¶¶¶¶¶¶¶¶¶¶")
print(MAGENTA+" ∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆")
print("")
print(BLANCO+"                                     Es un gusto poder ayudarte")
print("        1.  Matrices regla de cramer ")
print("        2.  Matrices por metodo de Gauss Jordan ")
print("        3.  Matrices por el metodo de Eliminaciok gaussiana ")
print("")
op = int(input("        Ingresa la opcion: "))
if op==1:
    os.system("clear")
    print(YELLOW+"")
    print("            ∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆")
    print("            ∆                                                              ∆ ")   
    print("            ∆  ∆∆ ∆∆ aaaaa aaaaa aaaaa aaaaa aaaaa    33333 3   3 33333    ∆" )   
    print("            ∆  ∆ ∆ ∆ a   a   a   a   a   a   a            3  3 3      3    ∆ " )  
    print("            ∆  ∆   ∆ a   a   a   a   a   a   aaaaa     3333   3    3333    ∆ "   )  
    print("            ∆  ∆   ∆ aaaaa   a   a a     a       a        3  3 3      3    ∆ ")
    print("            ∆  ∆   ∆ a   a   a   a  aa aaaaa aaaaa    33333 3   3 33333    ∆")
    print("            ∆                                                              ∆")
    print("            ∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆"    )   
    print(CYAN+"" )  
    print("")
    print("    ")
    print("                               Ingresa los valoras para: ")
    print("            ")
    print(BLANCO+"")
    print("                               [ a1    a2   a3  =  r1 ]  ")
    print("                               [                      ]                ")
    print("                               [ b1    b2   b3  =  r2 ]    ")
    print("                               [                      ]  ")
    print("                               [ c1    c2   c3  =  r3 ]  ")
    print("")
    print("")
    a1 = float(input("ingresa el valor de a1>> "))
    a2 = float(input("ingresa el valor de a2>> "))
    a3 = float(input("ingresa el valor de a3>> "))
    r1 = float(input("ingresa el valor de r1>> "))
    print("")
    print(" haz ingresado lo siguiente: ")
    print(RED+"      [ ",a1," ",a2," ",a3,"=  ",r1," ]"+BLANCO)
    print("")
    b1 = float(input("ingresa el valor de b1>> "))
    b2 = float(input("ingresa el valor de b2>> "))
    b3 = float(input("ingresa el valor de b3>> "))
    r2 = float(input("ingresa el valor de r2>> "))
    print("")                                                                                                       
    print(" haz ingresado lo siguiente: ")                                                                          
    print(BLUE+"      [ ",b1," ",b2," ",b3,"=  ",r2," ]"+BLANCO)
    print("")
    c1 = float(input("ingresa el valor de c1>> "))
    c2 = float(input("ingresa el valor de c2>> "))
    c3 = float(input("ingresa el valor de c3>> "))
    r3 = float(input("ingresa el valor de r3>> "))
    print("")
    print(" haz ingresado lo siguiente: ")
    print(CYAN+"      [ ",c1," ",c2," ",c3,"=  ",r3," ]"+BLANCO)
    print("")
    print("")
    print(YELLOW+"        😎 comencemos a trabajar 😎    ")
    print("")
    print("      [ ",a1," ",a2," ",a3," = ",r1," ]")
    print("")
    print("      [ ",b1," ",b2," ",b3," = ",r2," ]")
    print("")
    print("      [ ",c1," ",c2," ",c3," = ",r3," ]"+BLANCO)
    time.sleep(3)
    print("")
    print(RED+"Obtendremos el valor D")
    print("el procedimiento es el siguiente: ")
    print("D = (a1*((b2*c3)-(b3*c2)))-(a2*((b1*c3)-(b3*c1)))+(a3*((b1*c2)-(b2*c1)))")
    D = (a1*((b2*c3)-(b3*c2)))-(a2*((b1*c3)-(b3*c1)))+(a3*((b1*c2)-(b2*c1)))
    print("")
    print("el valor de D es: ",D)
    print("")
    time.sleep(3)
    print(YELLOW+"Ahora obtendremos el valor de X")
    print("El procedimiento es este: ")
    print("X =(((r1*((b2*c3)-(b3*c2)))-(a2*((b1*c3)-(b3*c1)))+(a3*((b1*c2)-(b2*c1))))/D)")
    print("")
    print("")
    print("     [ ",r1,"  ",a2," ",a3,"  ] ")
    print("")
    print(" x = [ ",r2,"  ",b2," ",b3,"  ]")
    print("")
    print("     [ ",r3,"  ",c2," ",c3,"  ]")
    print("     ___________________________  ")
    print("                 ",D)
    print("")
    X =(((r1*((b2*c3)-(b3*c2)))-(a2*((r2*c3)-(b3*r3)))+(a3*((r2*c2)-(b2*r3))))/D)
    print("El valor de X es: ",X)
    print("")
    print("")
    time.sleep(3)
    print(BLUE+"Ahora obtendremos el valor de Y")
    print("El procedimiento es este: " )
    print("Y = (((a1*((r2*c3)-(b3*r3)))-(r1*((b1*c3)-(b3*c1)))+(a3*((b1*r3)-(r2*c1))))/D)      ")
    print("")
    print("")
    print("    [ ",a1,"  ",r1,"  ",a3,"  ]")
    print("")
    print("    [ ",b1,"  ",r2," ",b3,"   ]")
    print("")
    print("    [ ",c1,"  ",r3," ",c3,"   ]")
    print("   ____________________________")
    print("                   ",D)
    print("")
    Y = (((a1*((r2*c3)-(b3*r3)))-(r1*((b1*c3)-(b3*c1)))+(a3*((b1*r3)-(r2*c1))))/D)
    print("El valor de Y es: ",Y)
    print("")
    print("")
    time.sleep(3)
    print(CYAN+"Ahora obtendremos el valor de Z")
    print("El procedimiento es este: ")
    print("      ")
    print("")
    print("")
    print("    [ ",a1,"  ",a2,"  ",r1,"   ]")
    print("")
    print("    [ ",b1,"  ",b2,"  ",r2,"   ]")
    print("")
    print("    [ ",c1,"  ",c2,"  ",r3,"   ]")
    print("   ____________________________")
    print("                   ",D)
    Z = (((a1*((b2*r3)-(r2*c2)))-(a2*((b1*r3)-(r2*c1)))+(r1*((b1*c2)-(b2*c1))))/D)
    print("El valor de Z es: ",Z)
    print("")
    print("")
    print(BLANCO+"Los resultados finales son:      ")
    time.sleep(2)
    print(RED+"El valor de D es: ",D)
    print(YELLOW+"El valor de X es: ",X)
    print(BLUE+"El valor de Y es: ",Y)
    print(CYAN+"El valor de Z es: ",Z)

elif op==2:
    os.system("clear")
    print("∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆")
    print("∆                                                                         ∆")
    print("∆  ∆∆∆∆∆ aaaaa a   a aaaaa aaaaa    aaaaa aaaaa aaaaa aaaa  aaaaa aaa a   ∆")
    print("∆  ∆     a   a a   a a     a          a   a   a a   a a   a a   a a a a   ∆")
    print("∆  ∆ ∆∆  a   a a   a aaaaa aaaaa      a   a   a a  a  a   a a   a a a a   ∆")
    print("∆  ∆   ∆ aaaaa a   a     a     a      a   a   a a   a a   a aaaaa a a a   ∆")         
    print("∆  ∆∆∆∆∆ a   a aaaaa aaaaa aaaaa    aaa   aaaaa a   a aaaa  a   a a aaa   ∆")
    print("∆                                                                         ∆")
    print("∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆∆")
    print("" )
    print("")
    print("    ")
    print("                 Ingresa los valoras para: ")      
    print("            ")
    print("                 [ a1    a2   a3  =  r1 ]  ")    
    print("                 [                      ]                ")
    print("                 [ b1    b2   b3  =  r2 ]    ")  
    print("                 [                      ]  ")
    print("                 [ c1    c2   c3  =  r3 ]  ")

else:
    print("eso no existe")

print("fin del programa")    

